= conjure-up User Manual
Adam Stokes <https://github.com/battlemidget[@battlemidget]>; Mike McCracken <https://github.com/mikemccracken[@mikemccracken]>
:toc: left
:toclevels: 4
:revnumber: 2.1.1
:revremark: Stable
:source-highlighter: pygments
:icons: font
:imagesdir: /images/walkthrough
:experimental:


*conjure-up* is a thin layer spanning a few different underlying
technologies - https://jujucharms.com[Juju], http://maas.io[MAAS],
and http://linuxcontainers.org[LXD].

*conjure-up* provides you with a streamlined, turnkey solution. In order
to provide that streamlined approach, *conjure-up* makes use of
processing scripts. These scripts are executed at 3 different times in
the deployment, just after a Juju bootstrap, just before a Juju deploy,
and right after a Juju deploy.

Processing scripts give you the flexibility to alter LXD profiles in
order to expose additional network interfaces to Neutron services,
import images into Glance once the service is available, or notifying
the Deployment status screen that your solution is ready and can be
viewed at a specific URL.

With these powerful concepts you can package up the solution that can
then be provided to coworkers who can easily deploy your solutions in
any Public Cloud, MAAS, or LXD.


[[getting-started]]
== Getting Started

[[hardware-requirements]]
=== Hardware Requirements

[[public-cloud]]
==== Public Cloud

For *Public Cloud* deployments hardware requirements(__constraints__)
are handled by the Spell authors and will automatically be allocated
during deploy.

[[localhost]]
==== Localhost

For *localhost* deployments the following setup is recommended:

* 2 cores
* 16G RAM
* 32G Swap
* 250G SSD with a seperate block device for ZFS. Our recommendation for
that device is 100G.

[[installing-conjure-up]]
=== Installing conjure-up

conjure-up is available on both Ubuntu Trusty 14.04 LTS and Ubuntu Xenial 16.04 LTS

[source,bash]
----
$ sudo snap install conjure-up --classic
----

NOTE: If above command fails you'll want to make sure **snapd** is installed with `apt-get install snapd`

[[install-trusty-caveat]]
==== Ubuntu Trusty 14.04

Trusty users will need to perform some additional steps prior to getting the snappy version installed.

To get a working conjure-up install on Trusty the following needs to be run:

[source,bash]
----
$ sudo apt-get install snapd
$ sudo groupadd lxd && sudo usermod -a -G lxd $USER
$ sudo reboot
$ sudo snap install conjure-up --classic
----

[[bleeding-edge]]
==== Betas, Development Versions

You can always test out the latest and greatest (though not necessarily stable) with:

[source,bash]
----
$ sudo snap install conjure-up --classic --edge
# Or
$ sudo snap install conjure-up --classic --beta
----

If you have **conjure-up** already installed simply run:

[source,bash]
----
$ sudo snap refresh conjure-up --classic --edge
# Or
$ sudo snap refresh conjure-up --classic --beta
----

[[a-note-for-lxd-users]]
==== Users of LXD

**conjure-up** currently only supports running a single installation of LXD.
Meaning, systems with LXD pre-installed like Ubuntu Xenial Server should not
have the snapped version of LXD installed.

NOTE: If you've never done anything with https://snapcraft.io/[snappy] before
feel free to skip this section.

You can opt to use either or as **conjure-up** will support LXD versions 2.0.8
and above. To verify that you do only have a single installation of LXD do the
following:

Check `snap list` output does not have **lxd** listed:

[source,bash]
----
$ snap list

Name  Version  Rev  Developer  Notes
core  16.04.1  888  canonical  -
----

If **lxd** is listed in the above output, make sure you do not have the Debian package installed:

[source,bash]
----
$ dpkg -l lxd
dpkg-query: no packages found matching lxd
----

In order to fix this problem you'll want to remove one of those:

For the snap version:

[source,bash]
----
$ sudo snap remove lxd
----

For the Debian package:
[source,bash]
----
$ sudo apt-get remove lxd lxd-client
$ sudo apt-get purge lxd
----


[[summon-a-spell]]
=== Summon a Spell

To deploy solutions such as OpenStack you will summon a spell:

[source,bash]
----
$ conjure-up openstack
----

To see a list of all available spells run:

[source,bash]
----
$ conjure-up
----

****
NOTE: Several remote locations are supported please see <<usage>>
for further details.
****

[[uninstalling]]
=== Uninstalling

To remove deployments:

[source,bash]
----
$ conjure-down
----

To uninstall **conjure-up** itself:

[source,bash]
----
$ sudo snap remove conjure-up
----

include::walkthrough.adoc[]
include::usage.adoc[]
include::troubleshoot.adoc[]
