= conjure-up User Manual
Adam Stokes <https://github.com/battlemidget[@battlemidget]>; Mike McCracken <https://github.com/mikemccracken[@mikemccracken]>
:toc: left
:toclevels: 4
:revnumber: 2.1.0
:revdate: 2017-01-27
:revremark: Stable
:source-highlighter: pygments
:icons: font
:imagesdir: /images/walkthrough
:experimental:


*conjure-up* is a thin layer spanning a few different underlying
technologies - https://jujucharms.com[Juju], http://maas.io[MAAS],
and http://linuxcontainers.org[LXD].

*conjure-up* provides you with a streamlined, turnkey solution. In order
to provide that streamlined approach, *conjure-up* makes use of
processing scripts. These scripts are executed at 3 different times in
the deployment, just after a Juju bootstrap, just before a Juju deploy,
and right after a Juju deploy.

Processing scripts give you the flexibility to alter LXD profiles in
order to expose additional network interfaces to Neutron services,
import images into Glance once the service is available, or notifying
the Deployment status screen that your solution is ready and can be
viewed at a specific URL.

With these powerful concepts you can package up the solution that can
then be provided to coworkers who can easily deploy your solutions in
any Public Cloud, MAAS, or LXD.


[[getting-started]]
== Getting Started

[[hardware-requirements]]
=== Hardware Requirements

[[public-cloud]]
==== Public Cloud

For *Public Cloud* deployments hardware requirements(__constraints__)
are handled by the Spell authors and will automatically be allocated
during deploy.

[[localhost]]
==== Localhost

For *localhost* deployments the following setup is recommended:

* 2 cores
* 16G RAM
* 32G Swap
* 250G SSD with a seperate block device for ZFS. Our recommendation for
that device is 100G.

[[installing-conjure-up]]
=== Installing conjure-up

conjure-up is available on both Ubuntu Trusty 14.04 LTS and Ubuntu Xenial 16.04 LTS

[source,bash]
----
$ sudo snap install conjure-up --classic --beta
----

[[install-trusty-caveat]]
==== Ubuntu Trusty 14.04

Trusty users will need to perform some additional steps prior to getting the snappy version installed.

To get a working conjure-up install on Trusty the following needs to be run:

[source,bash]
----
$ sudo apt-get install snapd
$ sudo groupadd lxd && sudo usermod -a -G lxd $USER
$ sudo reboot
$ sudo snap install conjure-up --classic --beta
----


[[summon-a-spell]]
=== Summon a Spell

To deploy solutions such as OpenStack you will summon a spell:

[source,bash]
----
$ conjure-up openstack
----

To see a list of all available spells run:

[source,bash]
----
$ conjure-up
----

****
NOTE: Several remote locations are supported please see <<usage>>
for further details.
****

[[uninstalling]]
=== Uninstalling

To remove deployments:

[source,bash]
----
$ conjure-down
----

To uninstall **conjure-up** itself:

[source,bash]
----
$ sudo snap remove conjure-up
----

include::walkthrough.adoc[]
include::usage.adoc[]
include::troubleshoot.adoc[]
