= conjure-up User Manual
Adam Stokes <https://github.com/battlemidget[@battlemidget]>; Mike McCracken <https://github.com/mmcc[@mikemccracken]>
:toc: left
:toclevels: 4
:revnumber: 2.1.0
:revdate: 2017-01-17
:revremark: Stable
:source-highlighter: pygments
:icons: font
:imagesdir: /images/walkthrough
:experimental:


*conjure-up* is a thin layer spanning a few different underlying
technologies - https://jujucharms.com[Juju], http://maas.io[MAAS],
and http://linuxcontainers.org[LXD].

*conjure-up* provides you with a streamlined, turnkey solution. In order
to provide that streamlined approach, *conjure-up* makes use of
processing scripts. These scripts are executed at 3 different times in
the deployment, just after a Juju bootstrap, just before a Juju deploy,
and right after a Juju deploy.

Processing scripts give you the flexibility to alter LXD profiles in
order to expose additional network interfaces to Neutron services,
import images into Glance once the service is available, or notifying
the Deployment status screen that your solution is ready and can be
viewed at a specific URL.

With these powerful concepts you can package up the solution that can
then be provided to coworkers who can easily deploy your solutions in
any Public Cloud, MAAS, or LXD.


[[getting-started]]
== Getting Started

[[hardware-requirements]]
=== Hardware Requirements

[[public-cloud]]
==== Public Cloud

For *Public Cloud* deployments hardware requirements(__constraints__)
are handled by the Spell authors and will automatically be allocated
during deploy.

[[localhost]]
==== Localhost

For *localhost* deployments the following setup is recommended:

* 2 cores
* 16G RAM
* 32G Swap
* 250G SSD with a seperate block device for ZFS. Our recommendation for
that device is 100G.

[[configure-lxdzfs]]
=== Configure LXD/ZFS

If you plan on using the *localhost* provider a properly configured
network bridge is required and optionally(**but highly recommended**)
configuring ZFS. Skip if you plan on using any other public cloud.

[source,bash]
----
$ sudo lxd init
----

LXD will go through a series of questions including the setup of ZFS and
a network bridge. Make sure to utilize your seperate block device for
the ZFS pool here.

NOTE: There may be times where conjure-up will error out due to
not finding a suitable **lxdbr0** bridge device. Since LXD is socket
activated you may need to run **lxc finger** and re-try conjure-up
installation.

TIP: For best results make sure to allocate at least a 100G ZFS
pool size.

TIP: If the installation fails please check that LXD is not enabled
with IPv6 as that is currently not supported.

[[installing-conjure-up]]
=== Installing conjure-up

[source,bash]
----
$ sudo apt-add-repository ppa:juju/stable
$ sudo apt-add-repository ppa:conjure-up/next
$ sudo apt update
$ sudo apt install conjure-up
$ conjure-up
----


[[summon-a-spell]]
=== Summon a Spell

To deploy solutions such as OpenStack you will summon a spell:

[source,bash]
----
$ conjure-up openstack
----

To see a list of all available spells run:

[source,bash]
----
$ conjure-up
----

****
NOTE: Several remote locations are supported please see <<usage>>
for further details.
****

[[uninstalling]]
=== Uninstalling

[source,bash]
----
$ conjure-down
----

include::walkthrough.adoc[]
include::usage.adoc[]
include::troubleshoot.adoc[]
