[[troubleshoot]]
== Troubleshoot

=== Logging

**conjure-up** logs are written to **journald** by default. Viewing those logs can be done with:

[source,bash]
----
$ journalctl |grep conjure-up
----

NOTE: There is also a log file that is written to **$HOME/.cache/conjure-up/conjure-up.log**

=== Unicode

If the system running **conjure-up** does not have its locale defined to **UTF-8** a failure will occur similar to:

[source,python]
----
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2201: ordinal not in range(128)
----

To fix you will need to set your locale accordingly, for example:

[source,bash]
----
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
----

== Common Spell Problems

=== LXD

==== Failed deployments if IPv6 is enabled

Currently conjure-up does not support the use of IPv6. If you are running LXD
and have a bridge that has IPv6 enabled conjure-up will fail and give you an
explanation as to why and information for disabling IPv6.

===== Disable IPv6 on LXD versions 2.2 and below

LXD version 2.0 is the default version on Ubuntu Xenial 16.04. To disable IPv6
you'll need to edit **/etc/default/lxd-bridge** and make sure the following
values are reflected below:

[source,ini]
----
# IPv6
## IPv6 address (e.g. 2001:470:b368:4242::1)
LXD_IPV6_ADDR=""

## IPv6 CIDR mask (e.g. 64)
LXD_IPV6_MASK=""

## IPv6 network (e.g. 2001:470:b368:4242::/64)
LXD_IPV6_NETWORK=""

## NAT IPv6 traffic
LXD_IPV6_NAT="false"
----

===== Disable IPv6 on LXD versions 2.4 and above

To disable IPv6 on your LXD bridge (**lxdbr0** by default) run the following:

[source,bash]
----
lxc network set lxdbr0 ipv6.nat false
lxc network set lxdbr0 ipv6.address none
----

=== OpenStack Base for MAAS

==== config-changed error for neutron-gateway

This error can happen if you've not set your **bridge-mappings** and
**data-port** during the <<application-list>> portion of the deployment.

Please see https://jujucharms.com/neutron-gateway/[the Neutron Gateway charm
documentation] under **Port Configuration** for more information.
