[[troubleshoot]]
== Troubleshoot

=== Logging

**conjure-up** logs are written to **journald** by default. Viewing those logs can be done with:

[source,bash]
----
$ journalctl |grep conjure-up
----

You can also increase the logging by enabling the **debug** flag:

[source,bash]
----
$ conjure-up -d
----

=== Unicode

If the system running **conjure-up** does not have its locale defined to **UTF-8** a failure will occur similar to:

[source,python]
----
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2201: ordinal not in range(128)
----

To fix you will need to set your locale accordingly, for example:

[source,bash]
----
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
----

== Common Spell Problems

=== OpenStack with NovaLXD

==== To many open files

There are times where a deployment of OpenStack on a single system will cause an
error of "To many open files" and normally shows up at the end of a deployment
when you've reached 14-15 running containers. There is a
https://bugs.launchpad.net/juju-release-tools/+bug/1631038[launchpad bug] to
address this. In the meantime, edit **/etc/sysctl.conf** with this workaround:


[source,bash]
----
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 256
----

Make sure to run `sysctl -p` to update those settings. Also see more information on https://github.com/lxc/lxd/blob/master/doc/production-setup.md[scaling LXD].

==== RabbitMQ Server: hook failed: "amqp-relation-changed" for _service_:amqp

This looks to be a race condition with Juju, LXD, cloud-init during the setting
of hostnames.
https://github.com/conjure-up/conjure-up/issues/489#issuecomment-253112250[This
bug] goes over the current state of the issue and links launchpad bugs for
tracking any fixes. A possible workaround is to deploy **RabbitMQ Server** first
from the Application list within **conjure-up** then deploy the remaining
applications after that.

=== OpenStack Base for MAAS

==== config-changed error for neutron-gateway

This error can happen if you've not set your **bridge-mappings** and
**data-port** during the <<application-list>> portion of the deployment.

Please see https://jujucharms.com/neutron-gateway/[the Neutron Gateway charm
documentation] under **Port Configuration** for more information.
