[[usage]]
== Advanced Spell Summoning

*conjure-up* includes several spells in addition to supporting summoning
spells from several remote repositories and from a local directory on
your filesystem.

[[githubbitbucket]]
=== GitHub/BitBucket

Not quite ready to push your spell to the charm registry? That's ok,
simply push your spell to GitHub and conjure-up can deploy from there:

....
$ conjure-up battlemidget/ghost
....

This would pull from GitHub repo https://github.com/battlemidget/ghost

[[remote-web-server]]
=== Remote Web Server

*conjure-up* will also support downloading directly from a webserver.
For example, if you have your spell zipped up and stored at
http://example.com/my-conjure-spell.zip you could install it like so:

....
$ conjure-up http://example.com/my-conjure-spell.zip
....

[[local-filesystem]]
=== Local Filesystem

Passing in either the directory path of the spell or if the current
working directory is a spell:

....
$ conjure-up ~/spells/openstack/openstack-novalxd
....

Or from *cwd*

....
$ ~/spells/openstack/openstack-novalxd> conjure-up .
....

[[running-in-headless-mode]]
=== Running in Headless Mode

*conjure-up* is meant to be a teaching tool in addition to a full blown
application deployment tool. By Default *conjure-up* will walk you
through the entire deployment process and help you understand what it is
you are deploying.

Where this doesn't make sense is if you are wanting to deploy your
application in an automated fashion. For example, integrating the
deployment with a Jenkins CI server.

For these cases *conjure-up* provides a headless mode.

To deploy in a headless mode you'll need to have credentials defined if
deploying to a Public Cloud or make sure LXD is configured if deploying
to Localhost.

To deploy OpenStack to a Localhost provider:

....
$ conjure-up openstack localhost
....

If we want to deploy to a cloud like AWS:

....
$ conjure-up observable-kubernetes aws
....

NOTE: Keep in mind you'll need to have credentials defined, see
https://jujucharms.com/docs/devel/credentials[Juju credentials] for more
details.
