= conjure-up Developers Manual
Adam Stokes <https://github.com/battlemidget[@battlemidget]>; Mike McCracken <https://github.com/mmcc[@mmcc]>
:toc: left
:toclevels: 4
:revnumber: 0.1
:revdate: 2016-09-12
:revremark: WIP
:source-highlighter: pygments
:icons: font

At the heart of **conjure-up** are spells. They consist of all the information
required to deploy your applications and walk the user through getting started
as quickly as possible.

There are 2 main parts that make up a spell. The first being a **Juju bundle**,
these are your blueprints for defining the amount of units for each application
along with any default configuration options you wish to expose to the user for
modification.

The second part is the additional data added to the spell to be **conjure-up**
enabled. This contains your metadata which describes the spell and a set of
steps that you define for a user to walkthrough. This allows you as a spell
author to ensure that a user can learn about your application and at the end
know exactly what to do next in order to make the most out of your application.

It is recommended to learn the <<spell-anatomy>>
in order to get started building your spell!

[[spell-anatomy]]
== Anatomy of a conjure-up spell

We will start with the directory layout of a typical spell. Some of this will be
familiar as we build on the existing Juju bundle specification.

[source,bash]
----
my-super-application>
   - bundle.yaml <1>
   - README.md
   - metadata.yaml <2>
   - steps/ <3>
     - 00_deploy-done
     - 00_pre-deploy
     - step-01_my_first_step
     - step-01_my_first_step.yaml
----
<1> More information on creating Juju https://jujucharms.com/docs/stable/charms-bundles[bundle files]
<2> <<spell-metadata>>
<3> Excutable scripts to be run prior to deployment, to check when a deployment is finished, and steps to be processed for configuring deployment. See <<spell-steps>> for more information.

[[spell-metadata]]
=== Spell Metadata

The spell metadata contains properties that are useful for conjure-up to process
certain aspects of a spell. Available properties are as follows:

friendly-name:: This is used during the spell selection within conjure-up.
cloud-whitelist:: A list of Public clouds available for a spell.
cloud-blacklist:: A list of Public clouds that are known to not work with a spell.
packages:: Additional `apt` packages required for spell.
options-whitelist:: Additional charm options to be exposed for editing within conjure-up.

.metadata.yaml example
[source,yaml]
----
cloud-whitelist:
- localhost
friendly-name: OpenStack with NovaLXD
options-whitelist:
  keystone:
  - admin-password
  lxd:
  - block-devices
  mysql:
  - max-connections
  neutron-gateway:
  - ext-port
  nova-compute:
  - virt-type
----

[[spell-steps]]
=== Steps

During a deployment, **conjure-up** will always check for and run a predefined set of scripts:

00_pre-deploy:: This script contains necessary instructions for configuring a system prior to a deployment.
00_deploy-done:: This script will contain instructions for verifying that deployment has finished and is ready for its next steps.
step-##_a_step:: This is an alpha numerical script that will be executed in order to perform any actions necessary to provide a turn key and usuable deployment.
